Make signable detector regex more specifc
trufflesecurity/trufflehog pull request #1065
Opened 2023-02-03 05:24 UTC by marcinantkiewicz

add \b to the regex to avoid matching ".. assignable: 123456.."

2023-02-03 05:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trufflesecurity/trufflehog?pullRequest=1065) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trufflesecurity/trufflehog?pullRequest=1065) before we can accept your contribution.<br/><hr/>**Marcin Antkiewicz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trufflesecurity/trufflehog?pullRequest=1065) it.</sub>

2023-02-10 00:47 UTC, dustin-decker requested changes

2023-02-10 00:47 UTC, dustin-decker commented on pkg/detectors/signable/signable.go
> +	return []string{"\bsignable"}
This is used for substring matching. You might be looking to modify the regex pattern in the file

2023-07-21 14:17 UTC, zricethezav commented
closing due to inactivity, feel free to reopen with the suggested changes @marcinantkiewicz

2023-07-21 14:17 UTC, closed without merging