Make OpenAI regex more specific
trufflesecurity/trufflehog pull request #1345
Opened 2023-05-18 19:29 UTC by nyanshak

* OpenAI keys are in the format 'sk-' + 20 alphanumeric chars + the magic string 'OpenAI' base64-encoded + 20 alphanumeric chars.

2023-05-19 21:52 UTC, ahrav approved these changes
Nice! Thanks for the improvement here Brendan 😃

2023-05-19 22:03 UTC, ahrav requested changes

2023-05-19 22:03 UTC, ahrav commented on pkg/detectors/openai/openai.go
> +	keyPat = regexp.MustCompile(`\b((?:sk)-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z-09]{20})\b`)
suggestion: Looks like a typo in the last character class, it should be `[a-zA-Z-0-9]` looks like we are missing a `-`

question: Is there a benefit in keeping the initial non-capture group? Could we remove it and get the same effect.
eg: `\b(sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z-0-9]{20})\b`

2023-05-20 00:02 UTC, dustin-decker commented
The keyword on L45 could be changed to `T3BlbkFJ`, which will be a bit more specific and prevent the regex code path from running as often.

2023-05-22 14:39 UTC, merged