PR 2 of 40
trufflesecurity/trufflehog pull request #1670
Opened 2023-08-26 04:46 UTC by ahrav

### Description:
Explain the purpose of the PR.

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

2023-09-12 00:58 UTC, dustin-decker commented on pkg/detectors/appointedd/appointedd.go
> +				if bodyBytes, err := io.ReadAll(res.Body); err == nil {
Suggestion: https://github.com/trufflesecurity/trufflehog/blob/main/pkg/common/utils.go#L42-L53 would be more efficient

2023-09-12 00:59 UTC, dustin-decker commented on pkg/detectors/apptivo/apptivo.go
> +					bodyBytes, err := ioutil.ReadAll(res.Body)
Suggestion: https://github.com/trufflesecurity/trufflehog/blob/main/pkg/common/utils.go#L42-L53 would be more efficient

2023-09-12 01:05 UTC, dustin-decker requested changes

2023-09-12 01:05 UTC, dustin-decker commented on pkg/detectors/atera/atera.go
> +					// Consider adding the []byte conversion here if the input also changed to a []byte.
Nit: comment seems incorrect

2023-09-12 01:05 UTC, dustin-decker commented on pkg/detectors/audd/audd.go
>  				bodyBytes, err := io.ReadAll(res.Body)
Suggestion: https://github.com/trufflesecurity/trufflehog/blob/main/pkg/common/utils.go#L42-L53 would be more efficient

2023-09-12 01:05 UTC, dustin-decker commented on pkg/detectors/auth0oauth/auth0oauth.go
> +						if !bytes.Contains(bodyBytes, []byte("access_denied")) {
Suggestion: https://github.com/trufflesecurity/trufflehog/blob/main/pkg/common/utils.go#L42-L53 would be more efficient

2023-09-12 01:05 UTC, dustin-decker commented on pkg/detectors/aws/aws.go
> +				canonicalRequest := string(method) + "\n" + string(canonicalURI) + "\n" + string(canonicalQuerystring) + "\n" + string(canonicalHeaders) + "\n" + string(signedHeaders) + "\n" + string(payloadHash
Many of these are already strings, same on L158

2023-09-25 19:17 UTC, zricethezav commented
Closing this set of PRs until they are all ready to be reviewed and merged

2023-09-25 19:17 UTC, closed without merging