Filter scans by GitHub repository visibility
trufflesecurity/trufflehog pull request #1777
Opened 2023-09-14 22:36 UTC by 0x736E

### Description:
Implementation of Filter scans to only public repositories #1483.

Adds "--visibility" commandline argument which enables filtering scanning based on GitHub repository visibility status by providing a comma separated list. Acceptable visibility configuration includes "public", "private" and "shared" .  For example, to only scan by repositories which are either private or shared: --visibility="private,shared". 

Default behaviour is not changed as no filtering is applied in the absense of user defined visibility filter configuration. 

Internally, a new ScanOptions object is created to represent GitHub specific scan options.

No new tests were created because there appears to be an absence of unit tests for credential verification, and the manner in which this feature works requires checking the user's credentials against a repository.

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

2023-09-20 17:19 UTC, zricethezav commented
Thanks for opening this PR @0x736E, would you mind fixing the merge conflict? We'll get a review on this soon.

2023-09-20 17:20 UTC, zricethezav commented on pkg/sources/github/scan_options.go
> +
small **nit**: delete the white space here

2023-09-20 17:20 UTC, zricethezav commented on pkg/sources/github/scan_options.go
> +
small **nit**: delete the white space here

2023-09-20 17:21 UTC, zricethezav commented
Overall, this PR LGTM and I think this is a useful feature. 

@ahrav @0x1 @mcastorina would any of you care to give this a review too?

2023-09-21 10:21 UTC, 0x736E commented
Merged with main and removed whitespace

2023-09-21 16:10 UTC, mcastorina requested changes

2023-09-21 18:18 UTC, 0x736E commented on pkg/sources/github/scan_options.go
> +}
That's a very good point, it shouldn't.

Unknown is more or less the result of an error in determining the visibility of a repo, for this use case it seems unwise to allow users to target only repos which cause errors.

2023-09-21 18:19 UTC, 0x736E commented on proto/source_metadata.proto
> +  _invalid = -1;
I wasn't particularly happy with this in the first instance, I will review it.

2023-09-21 18:21 UTC, 0x736E commented on pkg/sources/github/github.go
> +				if !slices.Contains(s.scanOptions.Visibility, vis) {
This is where using a PR as an excuse to learn a new language meets with reality. Thanks for the suggestion, I'll look into it and make the changes.

2023-09-21 18:23 UTC, 0x736E commented
I've reviewed your suggestions, I agree with them, so I'll make the appropriate changes and update this PR when ready.

2025-03-19 21:21 UTC, closed without merging