Detector-Competition-Feat: Add PayTm Payment Detector
trufflesecurity/trufflehog pull request #1904
Opened 2023-10-18 10:23 UTC by fumblehool

### Description:
PR to add [PayTm ](https://paytm.com/) Payment Detector

API Docs: https://business.paytm.com/docs/api/initiate-transaction-api/

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

2023-10-18 20:29 UTC, zricethezav commented
@fumblehool same goes for this PR, could you provide a passing test screenshot?

2023-10-30 20:48 UTC, zricethezav commented
@fumblehool would you mind fixing merge conflicts

2023-10-31 06:57 UTC, fumblehool commented
@zricethezav Updated the PR, please re-review 😄

2023-11-06 20:37 UTC, zricethezav approved these changes

2023-11-06 20:39 UTC, zricethezav commented on pkg/detectors/paytm/paytm.go
> +			payload := strings.NewReader(`{"requestType":"Payment","mid":"Mid-1234","websiteName":"Sample-website-name","orderId":"ORDERID_1234","callbackUrl":"http://localhost:3000/paytm","txnAmount":{"value
@fumblehool anyway we could have this not hit `https://securegw.paytm.in/theia/api/v1/initiateTransaction?`? Seems like there is a risk of sending funds

2023-11-06 20:48 UTC, zricethezav requested changes
revoking my approval because I have one question about the endpoint we're hitting

2023-11-20 20:08 UTC, zricethezav commented
Closing this due to inactivity

2023-11-20 20:08 UTC, closed without merging