Add a flag to disable ssl verify
trufflesecurity/trufflehog pull request #2905
Opened 2024-06-02 15:05 UTC by rgmz

### Description:
This creates an experimental flag to disable SSL verification for detectors. This is useful in corporate environments where [MITMing SSL traffic is common](https://security.stackexchange.com/questions/107542/is-it-common-practice-for-companies-to-mitm-https-traffic) and certificates are replaced with self-signed ones.

This implementation is an incomplete POC.

- [ ] There may not be total coverage for http clients
- [ ] Detectors that rely on third-party libraries likely need to be configured separately. 

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

2024-07-09 21:53 UTC, zricethezav commented
Slapping a draft label on this since it's an incomplete POC

2024-07-09 21:55 UTC, rgmz commented
It could use a review to determine whether it's worth putting any more effort into.

2024-07-09 22:03 UTC, ahrav commented
> It could use a review to determine whether it's worth putting any more effort into.

I like the idea, but I'm a bit nervous about the global variable. Is there a way to use the flag to construct the transport instead? I'm concerned that it's too easy for anyone to reach into the transport and change the TLSConfig. That being said, if others are okay with this approach, I won't object. 😅

2024-07-09 23:15 UTC, rgmz commented
> I like the idea, but I'm a bit nervous about the global variable. 

It's a bit of a smell. I couldn't think of an easier way to propagate such a value to multiple packages before the dependent code initializes.

2024-11-27 01:03 UTC, rgmz commented
Unfortunately, it seems this isn't possible. The hundreds of detectors with logic like `defaultClient = common.SaneHttpClient()` means that [`SaneHttpClient()`](https://github.com/trufflesecurity/trufflehog/blob/e6cc78b95ee7101193f7db828a32f8135306c28f/pkg/common/http.go#L229) gets invoked well before `init` in main.go.


As far as I'm aware, there's no equivalent to something like [Kotlin's `lazy { }` initializer](https://kotlinlang.org/docs/delegated-properties.html#lazy-properties). Would it be feasible to initialize the client on each `FromData` call instead?

2024-12-31 15:31 UTC, rgmz commented
> Unfortunately, it seems this isn't possible. The hundreds of detectors with logic like `defaultClient = common.SaneHttpClient()` means that [`SaneHttpClient()`](https://github.com/trufflesecurity/trufflehog/blob/e6cc78b95ee7101193f7db828a32f8135306c28f/pkg/common/http.go#L229) gets invoked well before `init` in main.go.
> 
> As far as I'm aware, there's no equivalent to something like [Kotlin's `lazy { }` initializer](https://kotlinlang.org/docs/delegated-properties.html#lazy-properties). Would it be feasible to initialize the client on each `FromData` call instead?

For this to work, the top-level var would need to be replaced with a lazy initialization.

https://github.com/trufflesecurity/trufflehog/blob/316316e60ef94093c481d6b70b402a253dc55ad5/pkg/detectors/scrapingbee/scrapingbee.go#L61-L63

2025-01-15 15:54 UTC, rosecodym requested changes
_In theory_, if you could toggle `ssl-verify` while the scan was running, changes to it wouldn't affect detectors that had already been initialized, right?

If so - and I really hate to be the bearer of bad news on this - that means the new feature flag operates differently from the other defined ones in a way that actually matters not to _you_ (or any other OSS user) but to TruffleHog Enterprise, which also uses this code. TruffleHog Enterprise runs as a persistent daemon, so we need the ability to dynamically toggle feature flags of running processes and have the changes be reflected. Having some flags require scanner restarts and other flags not require them is an accident waiting to happen.

I know this kind of sends you back to the drawing board, but I really want to avoid some future person a really irritating surprise.

(Or I'm misreading this and imagined a problem that doesn't exist!)

2025-01-15 16:38 UTC, rgmz commented
> _In theory_, if you could toggle `ssl-verify` while the scan was running, changes to it wouldn't affect detectors that had already been initialized, right?

That is correct for HTTP-based detectors. Non-HTTP detectors like MongoDB would work dynamically.

Detectors that use [`common.SaneClient()`](https://github.com/trufflesecurity/trufflehog/commit/4218c39d99b5f30153f62471c1be1c1596f0a4d4#diff-6cdf2ccf7c7d59da10b55c79b78ba31babff84f598ebd9e5720d57dc2d1c64a1R20) or [`detectors.DetectorHttpClientWithNoLocalAddresses`](https://github.com/trufflesecurity/trufflehog/pull/3221/files) create a singleton at start-up, either globally or per-detector. 'Fixing' this would require changing 800+ detectors to dynamically create HTTP clients, and that may have other implications. 

Since this pattern is [literally from the first commit of v3](https://github.com/trufflesecurity/trufflehog/commit/4218c39d99b5f30153f62471c1be1c1596f0a4d4), I think a change of that scale is probably outside of the scope of this. :/

2025-05-24 14:24 UTC, closed without merging