feat [detector]: added hasura detector
trufflesecurity/trufflehog pull request #3427
Opened 2024-10-16 10:34 UTC by sahil9001

### Description:
Relates to #3424 
This PR introduces a new detector for Hasura GraphQL Engine admin secrets. Hasura is a popular open-source engine that provides instant GraphQL APIs over databases. Detecting exposed Hasura admin secrets is crucial for preventing unauthorized access to GraphQL APIs and underlying databases.

We've finished up the work on the Hasura detector. It's a lot more reliable now. Here’s a quick rundown of what we did:

- **Cleaned up the code**: Rewrote the whole detector to make it simpler and easier to maintain. The main change was pulling all the API verification logic into its own separate function, which tidies things up considerably.
- **Made the verification much smarter**: Found a few quirks with the Hasura API that the detector now handles correctly:
  - The API sends a 200 OK status even for an invalid key. The detector is now smart enough to check the JSON response body for an errors message to confirm if the key is actually valid.
  - If a project domain doesn't exist, the API sends back a 500 error with a full HTML page. We made sure we catch this specific case, so we correctly mark the key as "not verified" instead of reporting a system error.

### Added better tests:
- Wrote a bunch of new "pattern tests" to confirm our regex logic is solid without having to hit the live API.
- We also rebuilt the main integration tests. They can now properly simulate tricky situations like network timeouts or unexpected API errors, so we know the detector can handle them.

Overall, the detector is in a much better place and is far more accurate than before. 

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

![hasura-detector-tests](https://github.com/user-attachments/assets/cbc6e01c-ffa2-45ef-beef-ec12154b07d0)

2024-10-16 14:47 UTC, sahil9001 commented
@rgmz This is ready for review, can you please check?

2024-10-16 15:24 UTC, ahrav commented
Oh wow, I can't believe we didn't have a Hasura detector. This is great, thanks @sahil9001 ❤️

2024-10-16 15:35 UTC, sahil9001 commented on pkg/detectors/hasura/hasura.go
> +		key := strings.TrimSpace(match[1])
I did use that only, which gave me this logic

2024-10-16 15:37 UTC, rgmz commented on pkg/detectors/hasura/hasura.go
> +		key := strings.TrimSpace(match[1])
Hmm, that doesn't make sense. The code in Alchemy is completely different from this, it was changed at least several months ago. :thinking:

2024-10-16 15:39 UTC, sahil9001 commented on pkg/detectors/hasura/hasura.go
> +		key := strings.TrimSpace(match[1])
yeah, my bad, I changed the logic from some other detector though, was just talking about the generation

2024-10-16 15:40 UTC, sahil9001 commented on pkg/detectors/hasura/hasura.go
> +		key := strings.TrimSpace(match[1])
Upon talking with Zach, I got to know that we are deprioritising adding a new detector code as it doesn't qualify for Hacktoberfest

2024-11-13 06:40 UTC, kashifkhan0771 requested changes
Conflicts needs to be resolved. Also please add pattern test cases and move the integration test cases in a separate file. Moving forward we will follow this for all new detectors.

2025-06-17 15:19 UTC, shahzadhaider1 commented
First off, a big thank you to @sahil9001 for the contribution and for building the solid foundation for this detector. Your initial work was a great starting point!

I've picked this up to move it forward, addressed the previous feedback from the team, and added a full suite of pattern and integration tests to ensure everything is solid.

@rgmz, @kashifkhan0771, and team, this is ready for a fresh review when you have a moment. Thanks!

2025-06-19 09:41 UTC, kashifkhan0771 requested changes

2025-06-19 09:41 UTC, kashifkhan0771 commented on pkg/detectors/hasura/hasura.go
> +			results = append(results, *verifiedResult)
```go
var uniqueKeyMatches, uniqueDomainMatches = make(map[string]struct{}), make(map[string]struct{})

	for _, match := range keyPat.FindAllStringSubmatch(dataStr, -1) {
		uniqueKeyMatches[match[1]] = struct{}{}
	}

	for _, match := range domainPat.FindAllStringSubmatch(dataStr, -1) {
		uniqueDomainMatches[match[1]] = struct{}{}
	}

	// Logic: For each key, try to verify against each found domain.
	// Stop and record a verified finding on the first successful match.
	for key := range uniqueKeyMatches {
		for domain := range uniqueDomainMatches {
			s1 := detectors.Result{
				DetectorType: detectorspb.DetectorType_Hasura,
				Raw:          []byte(key),
				RawV2:        fmt.Appendf([]byte(""), "%s:%s", domain, key),
			}

			if verify {
				isVerified, extraData, verificationErr := s.verifyHasura(ctx, s.getClient(), domain, key)
				s1.Verified = isVerified
				s1.ExtraData = extraData
				s1.SetVerificationError(verificationErr, key)
			}

			results = append(results, s1)
			// If we successfully verified this key with a domain, we don't need to check it against other domains.
			if s1.Verified {
				break
			}
		}
	}
```

2025-06-20 14:13 UTC, kashifkhan0771 approved these changes

2025-06-26 12:43 UTC, amanfcp approved these changes
Left a comment for discussion, rest looks good to me.

2025-06-26 12:43 UTC, amanfcp commented on pkg/detectors/hasura/hasura.go
> +	return false, extraData, fmt.Errorf("api returned 200 OK but response was inconclusive")
```
if response.Data != nil && len(response.Errors) == 0 {
    return true, extraData, nil
}
return false, extraData, nil
```

What would we miss in the code I've shared? :thinking:

2025-06-26 13:01 UTC, shahzadhaider1 commented on pkg/detectors/hasura/hasura.go
> +	return false, extraData, fmt.Errorf("api returned 200 OK but response was inconclusive")
updated

2025-06-26 13:11 UTC, merged