Feature/todo md generator
trufflesecurity/trufflehog pull request #3580
Opened 2024-11-09 13:51 UTC by snuweb

Title: feat: Add TODO.md generator for centralized TODO tracking

Closes #3508

## Description
This PR adds a script that automatically generates a centralized TODO.md file to track code-specific tasks and technical debt.

## Features
- 📊 Automatic TODO comment detection and categorization
- 📁 Package-based organization with collapsible sections
- 🔗 Direct links to code locations
- 📈 Statistics and summaries
- 🎯 Simple `make todo` command

## Sample Output
<img width="1232" alt="Screenshot 2024-11-09 at 14 51 08" src="https://github.com/user-attachments/assets/03e9712f-2b74-469a-b519-91f14f9d174b">

2024-11-09 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trufflesecurity/trufflehog?pullRequest=3580) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trufflesecurity/trufflehog?pullRequest=3580) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trufflesecurity/trufflehog?pullRequest=3580) it.</sub>

2024-11-11 05:35 UTC, kashifkhan0771 requested changes
Just a single script should be enough for listing TODO's. I don' think we need to put this much effort just for TODO's.

2024-11-11 08:08 UTC, snuweb commented
Thanks for the feedback! I put together a detailed TODO generator to make it easier for the team to keep track of tasks, with features like organized categories, package grouping, and direct links to code.

If this feels like overkill for just TODOs, I’m open to scaling it back. Would you prefer:

1. A basic version that:
   - Simply lists TODOs with file locations
   - Generates a simple markdown file
   - Uses a straightforward `make` command

2. A middle ground that still keeps:
   - File links for easy navigation
   - Basic categorization
   - A simple summary count

2024-11-11 14:59 UTC, zricethezav commented
Good ol, ctrl-f `TODO` works just fine

2024-11-11 14:59 UTC, closed without merging