added stormboard scanner
trufflesecurity/trufflehog pull request #367
Opened 2022-04-11 06:18 UTC by lonmarsDev

2022-04-24 01:02 UTC, dustin-decker requested changes

2022-04-24 01:02 UTC, dustin-decker commented on pkg/detectors/stormboard/stormboard.go
> +	"fmt"
It won't compile with this unused import. Also, the test seems to be failing right now.

2022-04-24 01:04 UTC, dustin-decker commented on pkg/detectors/stormboard/stormboard.go
> +	"fmt"
Oh the test failing might be my very slow wifi timing out. Please remove the unused import though.

2022-05-14 05:18 UTC, roxanne-tampus commented on pkg/detectors/stormboard/stormboard.go
> +	keyPat = regexp.MustCompile(detectors.PrefixRegex([]string{"stormboard"}) + `\b([a-z0-9]{40})\b`)
suggestion: this regex can be made a bit stricter by `\b([0-9a-f]{40})\b` as the keys are in hex encoding so we can only work with `a-f`.

2022-05-17 03:01 UTC, dustin-decker approved these changes

2022-05-17 03:01 UTC, merged