added appointed scanner
trufflesecurity/trufflehog pull request #425
Opened 2022-04-18 08:43 UTC by lonmarsDev

2022-04-24 01:55 UTC, dustin-decker requested changes
Please rename all instances of `appointed` to `appointedd`, including the package name

2022-04-24 01:55 UTC, dustin-decker commented on pkg/detectors/appointed/appointed.go
> +				if !strings.Contains(body, "Forbidden") {
Please invert this logic so that this can fail safe if there is a service outage. Check for something that would be in all successful responses.

2022-04-24 01:55 UTC, dustin-decker commented on pkg/detectors/appointed/appointed.go
> +	keyPat = regexp.MustCompile(detectors.PrefixRegex([]string{"appointed"}) + `\b([a-zA-Z0-9=]{88})`)
This is a base64 encoded credential. Base64 can also have `+` in the padding sometimes.

2022-04-24 01:55 UTC, dustin-decker commented on pkg/detectors/appointed/appointed.go
> +	keyPat = regexp.MustCompile(detectors.PrefixRegex([]string{"appointed"}) + `\b([a-zA-Z0-9=]{88})`)
This is a base64 encoded credential. Base64 can also have `+` in the padding sometimes.

2022-04-24 01:55 UTC, dustin-decker commented on pkg/detectors/appointed/appointed.go
> +	keyPat = regexp.MustCompile(detectors.PrefixRegex([]string{"appointed"}) + `\b([a-zA-Z0-9=]{88})`)
This is a base64 encoded credential. Base64 can also have `+` in the padding sometimes.

2022-05-14 06:44 UTC, roxanne-tampus commented on pkg/detectors/appointed/appointed.go
> +			req.Header.Add("X-API-KEY", fmt.Sprintf("%s", resMatch))
nit: Prefer to remove fmt.Sprintf and just use resMatch only here: req.Header.Add("X-API-KEY", resMatch)

2022-05-14 06:50 UTC, roxanne-tampus commented
Also, the detector itself is misspelled. Suggest to redo this starting by renaming the detector from `appointed `to `appointedd`.

2022-05-17 03:04 UTC, dustin-decker approved these changes

2022-05-17 03:05 UTC, dustin-decker commented
The test is no longer passing:

```$ go test github.com/trufflesecurity/trufflehog/v3/pkg/detectors/appointedd
--- FAIL: TestAppointedd_FromChunk (0.37s)
    --- FAIL: TestAppointedd_FromChunk/found,_verified (0.00s)
        appointedd_test.go:97: Appointedd.FromData() found, verified diff: (-got +want)
             [
            + {
            +  DetectorType: 816,
            +  Verified: true,
            +  Raw: [
            +  ],
            +  Redacted: "",
            +  ExtraData: {
            +  },
            +  StructuredData: nil,
            + },
             ]
    --- FAIL: TestAppointedd_FromChunk/found,_unverified (0.00s)
        appointedd_test.go:97: Appointedd.FromData() found, unverified diff: (-got +want)
             [
            + {
            +  DetectorType: 816,
            +  Verified: false,
            +  Raw: [
            +  ],
            +  Redacted: "",
            +  ExtraData: {
            +  },
            +  StructuredData: nil,
            + },
             ]
FAIL
FAIL	github.com/trufflesecurity/trufflehog/v3/pkg/detectors/appointedd	0.557s
FAIL
```

2022-05-17 03:06 UTC, dustin-decker requested changes
The test is no longer passing:

```$ go test github.com/trufflesecurity/trufflehog/v3/pkg/detectors/appointedd
--- FAIL: TestAppointedd_FromChunk (0.37s)
    --- FAIL: TestAppointedd_FromChunk/found,_verified (0.00s)
        appointedd_test.go:97: Appointedd.FromData() found, verified diff: (-got +want)
             [
            + {
            +  DetectorType: 816,
            +  Verified: true,
            +  Raw: [
            +  ],
            +  Redacted: "",
            +  ExtraData: {
            +  },
            +  StructuredData: nil,
            + },
             ]
    --- FAIL: TestAppointedd_FromChunk/found,_unverified (0.00s)
        appointedd_test.go:97: Appointedd.FromData() found, unverified diff: (-got +want)
             [
            + {
            +  DetectorType: 816,
            +  Verified: false,
            +  Raw: [
            +  ],
            +  Redacted: "",
            +  ExtraData: {
            +  },
            +  StructuredData: nil,
            + },
             ]
FAIL
FAIL	github.com/trufflesecurity/trufflehog/v3/pkg/detectors/appointedd	0.557s
FAIL
```

2022-08-25 17:37 UTC, dustin-decker approved these changes

2022-08-25 17:40 UTC, merged