added bulksms detector
trufflesecurity/trufflehog pull request #446
Opened 2022-04-22 05:00 UTC by lonmarsDev

2022-04-29 06:17 UTC, dustin-decker requested changes

2022-04-29 06:17 UTC, dustin-decker commented on pkg/detectors/bulksms/bulksms.go
> +	idPat = regexp.MustCompile(detectors.PrefixRegex([]string{"bulksmsId"}) + `\b([A-Z0-9-]{37})\b`)
`bulksmsId` is unlikely to be found. Just `bulksms`

2022-05-14 07:33 UTC, roxanne-tampus commented on pkg/detectors/bulksms/bulksms.go
> +	idPat = regexp.MustCompile(detectors.PrefixRegex([]string{"bulksms"}) + `\b([A-Z0-9-]{37})\b`)
suggestion: this regex can be made a bit stricter by `\b([A-F0-9-]{37})\b` as the keys are in hex encoding.

2022-05-17 03:07 UTC, dustin-decker approved these changes

2022-05-17 03:07 UTC, merged