PR to allow Scanning of Gitlab Groups
trufflesecurity/trufflehog pull request #789
Opened 2022-09-09 08:33 UTC by notaname2

A solution for issue https://github.com/trufflesecurity/trufflehog/issues/788

2022-09-09 08:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trufflesecurity/trufflehog?pullRequest=789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trufflesecurity/trufflehog?pullRequest=789) before we can accept your contribution.<br/><hr/>**Andrew Bailey** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trufflesecurity/trufflehog?pullRequest=789) it.</sub>

2022-09-09 21:47 UTC, dustin-decker commented on pkg/sources/gitlab/gitlab.go
> +				return nil, errors.Errorf("receivec error on listing group projects: %s\n", err)
nit: small typo here on `receivec`, should be `received`

2022-09-09 21:47 UTC, dustin-decker approved these changes
Other than the small typo, looks good to me! Thanks for the contribution!

2022-09-16 15:59 UTC, bill-rich requested changes

2024-05-01 19:29 UTC, zricethezav commented
Going to close this PR as it hasn't been active for more than a year and a half. Scanning GitLab groups is still a desired feature. https://github.com/trufflesecurity/trufflehog/issues/788. Feel free to reopen or open another PR once conflicts resolved and updates have been made.

2024-05-01 19:29 UTC, closed without merging