Adding Shopify detector
trufflesecurity/trufflehog pull request #875
Opened 2022-10-27 16:24 UTC by kstilwell

Specifically, this is adding Shopify access token detection. These tokens are used to authenticate with the Shopify admin API.

Some relevant links:
https://shopify.dev/apps/auth/admin-app-access-tokens
https://shopify.dev/api/admin/getting-started

2022-10-28 19:00 UTC, dustin-decker requested changes
Thanks for the contribution, @kstilwell!

If we use this endpoint for verification it should verify for any oauth scopes assigned to the app: https://shopify.dev/api/admin-rest/2022-10/resources/accessscope#get-admin-oauth-access-scopes

We could also use the response data to add extra information on the scopes that the credential has in the `ExtraData` field.

2022-11-02 14:59 UTC, kstilwell commented
Hey @dustin-decker, thanks for the feedback...made the changes you requested.

2022-11-03 00:44 UTC, dustin-decker approved these changes
Thanks Kevin, looks good now. We'll merge this soon after updating the protos.

2022-11-08 16:30 UTC, kstilwell commented
Hey @dustin-decker, just wanted to check if there was anything else you needed from me to get this merged.

2022-11-08 16:51 UTC, ahrav commented
> Hey @dustin-decker, just wanted to check if there was anything else you needed from me to get this merged.

Hey Kevin, looks like there is one linter warning in the detector file. I believe you should be able to omit the `fmt.Sprintf` since `key` is already a string. I can get it merged after that.

2022-11-08 16:53 UTC, ahrav commented on pkg/detectors/shopify/shopify.go
> +				req.Header.Add("X-Shopify-Access-Token", fmt.Sprintf("%s", key))
linter suggestion: We can omit the `fmt.Sprintf` here.

2022-11-09 00:21 UTC, merged